// ===========================================================================
// File: /logic/student.js
// Description: Export API functions that handle requests at /api/student/*
// Author:
// Last updated: Feb 12 2017
// ===========================================================================

// ===============================================================================================================================================
//    Path                    |   Method    |   Purpose / Brief Description
// ===============================================================================================================================================
//                                   Student (USA + UPV + MS + MUP)
// ===============================================================================================================================================
//    /api/student/           |   POST      |   Create a student with criteria(JSON) in request body
//    /api/student/:id        |   PUT       |   Modify a student defined by id with new criteria(JSON) in request body
//    /api/student/:id        |   DELETE    |   Delete a student defined by id
//    /api/student/:id        |   GET       |   Get profile of a student as JSON object
//    /api/student/friend/:id |   GET       |   Get a list of friends (name, profile pic, id) of user defined by id
// ===============================================================================================================================================

var general = require('./general');
var Student = general.Student;
var ClassStudent = general.ClassStudent;
var StudentStudyHabit = general.StudentStudyHabit;


// ================================================================================
//  Function: postStudent
//  REST: POST:/api/student/
//  Description:
//  Expected input (req.body):
//  		- _id : id String auto generated by firebase 
//          - Email : String
//          - FirstName : String
//			- LastName : String
//			- Age : int
//			- Bio : String
//			- Email : String
//			- Major : String
//			- Class : [String]
// 			- Habit : [String]
//  Expected output (res):
//          - respond code: 200 for created (success), user added to database
//							400 for failed
//  Author: Minh Tran Quoc
// ================================================================================
module.exports.postStudent = function (req, res) {
	
	var ref = req.body;

	// Put necessary fields into a student model.
	var newStudent = Student({
		_id: ref._id;
		Email: ref.email,
		FirstName: ref.firstName,
		LastName: ref.lastName,
		Age: ref.age
		Bio: ref.bio,
		Major: ref.major
	});

	// Create it in database
	newStudent.save(function(err) {

		// Couldn't create student
		if (err) {
			console.log('Can not create new student in mongodb');
			res.sendStatus(400);
		}

		// Student created, making studentclass relationships
		ref.class.forEach(function (each) {

			// Find to see if the habit is a valid habit in database
			Class.find({"Name": each}, function(err, thisClass) {

				// Not a valid class
				if (err) {
					console.log('Can not find class ' + each);
					res.sendStatus(400);
				}

				// Valid habit, create StudyHabitStudent relationship
				var studyHabitStudent = ClassStudent({
					StudentID: ref._id;
					ClassID: thisClass._id;
				});

				classStudent.save(function(err) {
					if (err) {
						console.log('Can not create new ClassStudent in mongodb');
						res.sendStatus(400);
					}
				});
			});
		});

		// Create student habit relationships for each habit
		ref.habit.forEach(function (each) {

			// Find if the class is valid
			Class.find({"Habit": each}, function(err, habit) {

				// Class not valid
				if (err) {
					console.log('Can not find study habit ' + each);
					res.sendStatus(400);
				}

				// Found study habit, making StudentStudyHabit relationship
				var studentStudyHabit = StuedntStudyHabit({
					StudentID: ref._id;
					Habit: each;
				});

				// Put it in database
				studentStudyHabit.save(function(err) {
					// Couldn't create ?
					if (err) {
						console.log('Can not create new studentStudyHabit in mongodb');
						res.sendStatus(400);
					}
				});
			});
		});
		
		// All good! Student created with necessary info. return success !
		res.sendStatus(200);

	});
};


// ================================================================================
//  Function: putStudentWithId
//  REST: PUT:/api/student/:id
//  Description: Change the information of an existing user
//  Expected input
//			(req.params.id): the id of user being changed
//			(req.body): new information in JSON format, including: 
//        		- Email : String
//        		- FirstName : String
//				- LastName : String
//				- Age : int
//				- Bio : String
//				- Email : String
//				- Major : String
//				- Class : String array
// 				- Habit : String array
//  Expected output (res):
//          - respond code: 200 for created (success), user modified in database
//							400 for failed
//  Author: Minh Tran Quoc
// ================================================================================
module.exports.putStudentWithId = function (req, res) {

};


// ================================================================================
//  Function: deleteStudentWithId
//  REST: DELETE:/api/student/:id
//  Description: delete profile of an user
//  Expected input (req.params.id): id of the user being deleted
//  Expected output (res):
//          - respond code: 200 for created (success), user data emptied, but not deleted
//							400 for failed
//  Author: Minh Tran Quoc
// ================================================================================
module.exports.deleteStudentWithId = function (req, res) {
};


// ================================================================================
//  Function: getStudentWithId
//  REST: GET:/api/student/:id
//  Description:
//  Expected input (req.body):
//  Expected output (res):
//  Author: Ruohan Hu
// ================================================================================
module.exports.getStudentWithId = function (req, res) {
	var studentID = req.params.id;
	
	// get a user with the ID
	User.findById(studentID, function(err, user) {
		if (err) throw err;
		// show the user
		console.log(user);
	});
};


// ================================================================================
//  Function: getStudentFriendWithId
//  REST: GET:/api/student/friend/:id
//  Description:
//  Expected input (req.body):
//  Expected output (res):
//  Author: Ruohan Hu
// ================================================================================
module.exports.getStudentFriendWithId = function (req, res) {
	var stduentFriendID = req.params.id;

	// get a user with the ID
	User.findById(studentFriendID, function(err, user) {
		if (err) throw err;
		// show the user
		console.log(user);
	});
};